name: CodeBuild Multi-Stage Pipeline

on:
  push:
    branches:
      - main  # Triggers automatically on push to main

  workflow_dispatch:
    inputs:
      debug:
        description: "Enable Debug Mode?"
        required: true
        type: choice
        options:
          - "true"
          - "false"
      log_level:
        description: "Log Level"
        required: false
        default: "info"
        type: choice
        options:
          - "info"
          - "debug"
          - "warn"
          - "error"

jobs:
  build:
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print GitHub Context
        run: echo "Running on AWS CodeBuild"

      - name: Build
        run: |
          echo "Building project..."
          sleep 5  # Simulating a build step
          echo "Build complete!"

      - name: Save Build Artifacts
        run: |
          mkdir -p build_artifacts
          echo "Build output" > build_artifacts/output.txt
          echo "Build successful" > build_artifacts/status.txt
        shell: bash

  test:
    needs: build
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 3  # Simulating test execution
          echo "Tests complete!"

      - name: Test Results
        run: |
          echo "All tests passed!"
        shell: bash

  deploy:
    needs: test
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Deployment Parameters
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          DEBUG_MODE="${{ github.event.inputs.debug || 'false' }}"
          LOG_LEVEL="${{ github.event.inputs.log_level || 'info' }}"
          
          echo "Deploying to environment: $ENV"
          echo "Debug Mode: $DEBUG_MODE"
          echo "Log Level: $LOG_LEVEL"
          
          # Export variables for later use
          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "DEBUG_MODE=$DEBUG_MODE" >> $GITHUB_ENV
          echo "LOG_LEVEL=$LOG_LEVEL" >> $GITHUB_ENV
        shell: bash

      - name: Deploy Application
        run: |
          echo "Starting deployment..."
          echo "Target Environment: $ENV"
          echo "Debug Mode Enabled: $DEBUG_MODE"
          echo "Using Log Level: $LOG_LEVEL"
          
          sleep 3  # Simulating deployment process

          if [[ "$DEBUG_MODE" == "true" ]]; then
            echo "Debugging enabled! Running extra logs..."
            # Simulate debug logging
            echo "Debugging details..."
          fi

          echo "Deployment to $ENV complete!"
        shell: bash