name: CodeBuild Multi-Stage Pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger on

jobs:
  build:
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print GitHub Context
        run: echo "Running on AWS CodeBuild"

      - name: Build
        run: |
          echo "Building project..."
          sleep 5  # Simulating a build step
          echo "Build complete!"

      - name: Save Build Artifacts
        run: |
          mkdir -p build_artifacts
          echo "Build output" > build_artifacts/output.txt
          echo "Build successful" > build_artifacts/status.txt
        shell: bash

  test:
    needs: build
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."
          sleep 3  # Simulating test execution
          echo "Tests complete!"

      - name: Test Results
        run: |
          echo "All tests passed!"
        shell: bash

  deploy:
    needs: test
    runs-on: codebuild-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          echo "Deploying application..."
          sleep 3  # Simulating deployment process
          echo "Deployment complete!"
        shell: bash